[build]
  command = "yarn build"
  publish = "public"
  functions = "functions"


[dev]
  framework = "gatsby"


[[redirects]]
from = "/"
to = "/app"
status = 301
force = true


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true